global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#nikita_morozov'
