---
#https://docs.docker.com/compose/install/
version: '3.3'
services:

  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
       aliases:
       - post_db
       - comment_db

  ui:
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${HOST_PORT}:${APP_PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${POST_VER}
    networks:
      back_net:
       aliases:
       - comment
      front_net:
       aliases:
       - comment

  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      back_net:
       aliases:
       - post
      front_net:
       aliases:
       - post

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'#время хранения метрик
    networks:
      - back_net
      - front_net


  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net

volumes:
  prometheus_data:
  post_db:
networks:
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.69.96.0/24
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.96.69.0/24
