---
version: '3.3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net
      - front_net

  elasticsearch:
    image: elasticsearch:5.6.16-alpine
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - back_net
      - front_net

  kibana:
    image: kibana:5.6.16
    ports:
      - "5601:5601"
    networks:
      - back_net
      - front_net

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - back_net
      - front_net

networks:
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.69.96.0/24
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.96.69.0/24
