---
version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
       aliases:
       - post_db
       - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${HOST_PORT}:${APP_PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
      back_net:
       aliases:
       - comment
      front_net:
       aliases:
       - comment
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      back_net:
       aliases:
       - post
      front_net:
       aliases:
       - post
volumes:
  post_db:
networks:
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.69.96.0/24
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.96.69.0/24
